use_frameworks!

platform :ios, '11.0'

target 'YuntongxunIM_Example' do
  pod 'YuntongxunIM/YuntongxunIMLibCore', :path => '../'

  target 'YuntongxunIM_Tests' do
    inherit! :search_paths

    
  end
end
